spring:
  config:
    activate:
      on-profile: test # 이 설정은 'test' 프로필일 때만 동작

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: "TEST_DUMMY_KEY_1234"