spring:
  datasource:
    # AWS RDS 운영용 엔드포인트 (명시적으로)
    url: jdbc:mysql://otakuzi-db.crwqqswce3v5.ap-northeast-2.rds.amazonaws.com/otakuzi?useSSL=true&requireSSL=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # ✅ 이건 그대로 OK
    show-sql: false

logging:
  level:
    root: ERROR
    com.otakuzi: INFO

management:
  endpoint:
    health:
      show-details: never