spring:
  datasource:
    # AWS RDS 개발용 엔드포인트
    url: jdbc:mysql://otakuzi-db.crwqqswce3v5.ap-northeast-2.rds.amazonaws.com:3306/otakuzi?useSSL=true&requireSSL=true&serverTimezone=UTC
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.otakuzi: DEBUG