spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: software.amazon.jdbc.Driver
    # AWS RDS 개발용 엔드포인트
    url: ${RDS_URL}
    username: ${DB_USERNAME}
    password: "dummy_password" # 비밀번호는 AWS가 알아서 넣으므로 가짜 값
    hikari:
      data-source-properties:
        wrapperPlugins: "secretsManager" # 플러그인 활성화
        secretsManagerSecretName: ${RDS_SECRET}

  jpa:
    hibernate:
      ddl-auto: validate