# 애플리케이션 이름
spring:
  application:
    name: otakuzi-backend

  # 활성 프로파일 (환경변수로 제어, 기본값은 dev)
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # JPA 공통 설정
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  config:
    # 'optional:'을 붙이면 파일이 없어도 에러가 안 납니다. (배포 환경을 위해 필수)
    import: optional:classpath:application-secret.yml

# 서버 포트
server:
  port: 8080

# Actuator 설정 (헬스체크용)
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always