spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: software.amazon.jdbc.Driver
    url: ${RDS_URL}
    username: ${RDS_SECRET}
    password: "dummy_password"

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  hikari:
    data-source-properties:
      wrapperPlugins: "secretsManager"

logging:
  level:
    root: ERROR           # 에러만 기록
    com.otakuzi: INFO     # 내 비즈니스 로직은 정보까지 기록

management:
  endpoint:
    health:
      show-details: never # 보안상 상세 정보 숨김