spring:
  datasource:
    driver-class-name: software.amazon.jdbc.Driver
    # AWS RDS 배포용 엔드포인트
    url: ${RDS_URL_PROD}?useAwsIam=true
    username: ${DB_USERNAME}
    password: "" # 비밀번호는 AWS가 알아서 넣으므로 가짜 값

    hikari:
      data-source-properties:
        useAwsIam: "true"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: https://www.otakuim.com/oauth/callback/kakao

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    root: ERROR           # 에러만 기록
    com.otakuzi: INFO     # 내 비즈니스 로직은 정보까지 기록

management:
  endpoint:
    health:
      show-details: never # 보안상 상세 정보 숨김