name: Deploy Backend (Prod)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # 빌드 테스트 
      - name: Build and Test using Docker (TDD Check)
        run: docker build -f backend/Dockerfile.test -t test-build .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/otakuzi-backend:prod

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            
            docker pull ${{ secrets.DOCKER_USERNAME }}/otakuzi-backend:prod
            
            docker stop backend-prod || true
            docker rm backend-prod || true
            
            docker run -d -p 8080:8080 --name backend-prod \
              --restart always \
              -e TZ=Asia/Seoul \
              -e JAVA_OPTS="-Xms256m -Xmx384m" \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e RDS_URL="${{ secrets.RDS_URL }}" \
              -e RDS_SECRET="${{ secrets.RDS_SECRET }}" \
              -e KAKAO_CLIENT_ID="${{ secrets.KAKAO_CLIENT_ID }}" \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
              -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
              --log-driver=awslogs \
              --log-opt awslogs-region=ap-northeast-2 \
              --log-opt awslogs-group=/otakuzi/app \
              --log-opt awslogs-stream=prod \
              --log-opt awslogs-create-group=true \
              ${{ secrets.DOCKER_USERNAME }}/otakuzi-backend:prod
            
            docker image prune -f